"""Build, benchmark, and optimize agentic skills for Python packages."""

from importlib.metadata import version

from acumen.agents import (
    AgentError,
    AgentOptions,
    AgentProvider,
    AgentResult,
    check_agent_cli,
    claude_sdk_available,
    provider_for_model,
    run_agent,
)
from acumen.bench import BenchmarkInvalidError, PlannedRun, build_matrix, pending, run_matrix, summarize
from acumen.config import Config, ConfigError, load_config, parse_config
from acumen.draft import DraftError, DraftResult, draft_skill
from acumen.env import (
    AuthMode,
    EnvError,
    Target,
    api_auth_available,
    build_agent_env,
    prepare_target,
    resolve_auth_mode,
    scrubbed_env,
    session_auth_available,
)
from acumen.grade import Grade, Reason, grade_answer, grade_run
from acumen.improve import (
    ImproveError,
    ImproveResult,
    TrainRun,
    collect_train_runs,
    find_test_access,
    improve_skill,
    make_test_guard,
)
from acumen.logs import LiveLog
from acumen.paths import RunKey, Split, arm_name, is_complete, parse_run_dir, run_dir, skill_from_arm
from acumen.report import (
    Report,
    ReportError,
    SkillTests,
    arm_metrics,
    build_report,
    load_results,
    resolve_palette,
    skill_tests,
    tradeoff_figure,
)
from acumen.runner import RunOutcome, run_once
from acumen.sandbox import Sandbox, install_skill, sandbox
from acumen.scaffold import InitError, scaffold
from acumen.ship import ShipError, ShipResult, installer_exists, ship_skill
from acumen.skills import (
    Skill,
    SkillError,
    SkillMeta,
    available_versions,
    latest_version,
    load_skill,
    next_version,
    skill_content,
    skill_hash,
)
from acumen.taskgen import (
    TaskGenError,
    TaskGenResult,
    build_filtered_source,
    dump_tasks,
    find_skill_access,
    generate_tasks,
    make_skill_guard,
)
from acumen.tasks import Task, TaskError, TaskSplit, load_tasks, parse_tasks
from acumen.transcript import (
    locate_transcript,
    render_agent_transcript,
    render_codex_transcript,
    render_transcript,
)

__all__ = [
    "AuthMode",
    "AgentError",
    "AgentOptions",
    "AgentProvider",
    "AgentResult",
    "BenchmarkInvalidError",
    "Config",
    "ConfigError",
    "DraftError",
    "DraftResult",
    "EnvError",
    "Grade",
    "ImproveError",
    "ImproveResult",
    "InitError",
    "LiveLog",
    "PlannedRun",
    "Reason",
    "Report",
    "ReportError",
    "RunKey",
    "RunOutcome",
    "Sandbox",
    "ShipError",
    "ShipResult",
    "Skill",
    "SkillError",
    "SkillMeta",
    "Split",
    "Target",
    "Task",
    "TaskError",
    "TaskGenError",
    "TaskGenResult",
    "TaskSplit",
    "TrainRun",
    "__version__",
    "api_auth_available",
    "arm_metrics",
    "arm_name",
    "available_versions",
    "check_agent_cli",
    "claude_sdk_available",
    "build_agent_env",
    "build_filtered_source",
    "build_matrix",
    "build_report",
    "collect_train_runs",
    "draft_skill",
    "dump_tasks",
    "find_skill_access",
    "find_test_access",
    "generate_tasks",
    "grade_answer",
    "grade_run",
    "improve_skill",
    "install_skill",
    "installer_exists",
    "is_complete",
    "make_skill_guard",
    "make_test_guard",
    "latest_version",
    "load_config",
    "locate_transcript",
    "load_results",
    "load_skill",
    "load_tasks",
    "next_version",
    "parse_config",
    "parse_run_dir",
    "parse_tasks",
    "pending",
    "prepare_target",
    "provider_for_model",
    "render_agent_transcript",
    "render_codex_transcript",
    "render_transcript",
    "resolve_auth_mode",
    "resolve_palette",
    "run_dir",
    "run_agent",
    "run_matrix",
    "run_once",
    "sandbox",
    "scaffold",
    "scrubbed_env",
    "session_auth_available",
    "ship_skill",
    "SkillTests",
    "skill_content",
    "skill_from_arm",
    "skill_hash",
    "skill_tests",
    "summarize",
    "tradeoff_figure",
]

__version__ = version("acumen")
