"""Build, benchmark, and optimize agentic skills for Python packages."""

from importlib.metadata import version

from acumen.agents import (
    AgentError,
    AgentOptions,
    AgentProvider,
    AgentResult,
    check_agent_cli,
    claude_sdk_available,
    provider_for_model,
    run_agent,
)
from acumen.bench import BenchmarkInvalidError, PlannedRun, build_matrix, pending, run_matrix, summarize
from acumen.check import (
    CheckError,
    CheckResult,
    CheckStatus,
    CheckSummary,
    ScriptRun,
    check_task_split,
    check_tasks,
    import_probe,
    orphan_scripts,
    run_reproducer,
    script_path,
    select_tasks,
    summarize_checks,
)
from acumen.config import Config, ConfigError, load_config, parse_config
from acumen.env import (
    AuthMode,
    EnvError,
    Target,
    api_auth_available,
    build_agent_env,
    prepare_target,
    resolve_auth_mode,
    scrubbed_env,
    session_auth_available,
)
from acumen.epoch import EpochPlan, resolve_epoch
from acumen.grade import Grade, Reason, grade_answer, grade_run
from acumen.improve import (
    ImproveError,
    ImproveResult,
    find_valid_access,
    improve_skill,
    make_valid_guard,
)
from acumen.logs import LiveLog
from acumen.paths import RunKey, Split, arm_name, is_complete, parse_run_dir, run_dir, skill_from_arm
from acumen.report import (
    Report,
    ReportError,
    SkillTests,
    arm_metrics,
    build_report,
    load_results,
    resolve_palette,
    skill_tests,
    tradeoff_figure,
)
from acumen.review import (
    ReviewError,
    ReviewResult,
    ReviewStatus,
    ReviewVerdict,
    parse_reviews,
    review_tasks,
    write_packet,
)
from acumen.runner import RunOutcome, run_once
from acumen.sandbox import Sandbox, install_skill, sandbox
from acumen.scaffold import InitError, scaffold
from acumen.scrub import (
    build_filtered_source,
    find_guidance,
    find_skill_access,
    make_skill_guard,
    scrub_venv,
)
from acumen.ship import ShipError, ShipResult, installer_exists, ship_skill
from acumen.skills import (
    Skill,
    SkillError,
    SkillMeta,
    available_versions,
    latest_version,
    load_skill,
    next_version,
    skill_content,
    skill_hash,
)
from acumen.taskgen import (
    Harvest,
    TaskGenError,
    TaskGenResult,
    dump_tasks,
    generate_tasks,
    harvest_scripts,
)
from acumen.tasks import Task, TaskError, TaskSplit, load_tasks, parse_tasks
from acumen.training import (
    EpochRow,
    best_version,
    build_training_rows,
    epochs_since_best,
    patience_exhausted,
    write_training_csv,
)
from acumen.trajectory import Trajectory, render_trajectory
from acumen.transcript import (
    build_trajectory,
    locate_transcript,
    render_agent_transcript,
    render_codex_transcript,
    render_transcript,
)
from acumen.wiki import (
    RunRecord,
    TaskWikiResult,
    WikiError,
    collect_arm_runs,
    recorded_arms,
    update_wiki,
)

__all__ = [
    "EpochRow",
    "build_training_rows",
    "write_training_csv",
    "patience_exhausted",
    "best_version",
    "epochs_since_best",
    "EpochPlan",
    "resolve_epoch",
    "find_valid_access",
    "make_valid_guard",
    "RunRecord",
    "TaskWikiResult",
    "WikiError",
    "collect_arm_runs",
    "recorded_arms",
    "update_wiki",
    "AuthMode",
    "AgentError",
    "AgentOptions",
    "AgentProvider",
    "AgentResult",
    "BenchmarkInvalidError",
    "CheckError",
    "CheckResult",
    "CheckStatus",
    "CheckSummary",
    "Config",
    "ConfigError",
    "EnvError",
    "Grade",
    "Harvest",
    "ImproveError",
    "ImproveResult",
    "InitError",
    "LiveLog",
    "PlannedRun",
    "Reason",
    "Report",
    "ReportError",
    "ReviewError",
    "ReviewResult",
    "ReviewStatus",
    "ReviewVerdict",
    "RunKey",
    "RunOutcome",
    "Sandbox",
    "ScriptRun",
    "ShipError",
    "ShipResult",
    "Skill",
    "SkillError",
    "SkillMeta",
    "Split",
    "Target",
    "Task",
    "TaskError",
    "TaskGenError",
    "TaskGenResult",
    "TaskSplit",
    "Trajectory",
    "__version__",
    "api_auth_available",
    "arm_metrics",
    "arm_name",
    "available_versions",
    "check_agent_cli",
    "claude_sdk_available",
    "build_agent_env",
    "build_filtered_source",
    "build_trajectory",
    "find_guidance",
    "build_matrix",
    "build_report",
    "check_task_split",
    "check_tasks",
    "dump_tasks",
    "find_skill_access",
    "generate_tasks",
    "grade_answer",
    "grade_run",
    "harvest_scripts",
    "import_probe",
    "improve_skill",
    "install_skill",
    "installer_exists",
    "is_complete",
    "make_skill_guard",
    "latest_version",
    "load_config",
    "locate_transcript",
    "load_results",
    "load_skill",
    "load_tasks",
    "next_version",
    "orphan_scripts",
    "parse_config",
    "parse_reviews",
    "parse_run_dir",
    "parse_tasks",
    "pending",
    "prepare_target",
    "provider_for_model",
    "render_agent_transcript",
    "render_codex_transcript",
    "render_trajectory",
    "render_transcript",
    "resolve_auth_mode",
    "resolve_palette",
    "review_tasks",
    "run_dir",
    "run_agent",
    "run_matrix",
    "run_once",
    "run_reproducer",
    "sandbox",
    "scaffold",
    "script_path",
    "scrub_venv",
    "scrubbed_env",
    "select_tasks",
    "session_auth_available",
    "ship_skill",
    "SkillTests",
    "skill_content",
    "skill_from_arm",
    "skill_hash",
    "skill_tests",
    "summarize",
    "summarize_checks",
    "tradeoff_figure",
    "write_packet",
]

__version__ = version("acumen")
